PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  up:   <http://purl.uniprot.org/core/>

SELECT DISTINCT  ?protein
WHERE
  { ?protein  a                     up:Protein ;
              rdfs:label            ?label
  }
ORDER BY ?label