PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?customer
WHERE
  { GRAPH ?doc
      { ?customer  a                schema:Corporation ;
                  schema:legalName  ?companyName
        GRAPH ?orderDoc
          { ?order  schema:customer  ?customer }
      }
  }
ORDER BY ?companyName