PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?order
WHERE
  { GRAPH ?doc
      { ?order  a                  schema:Order ;
                schema:identifier  ?orderID ;
                schema:orderDate   ?orderDate ;
                schema:customer    ?customer ;
                schema:broker      ?employee
      }
  }
ORDER BY ?orderID