PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT
{
    ?this skos:inScheme [ a skos:ConceptScheme ] ;
        skos:topConceptOf [ a skos:ConceptScheme ] ;
        skos:prefLabel [ a xsd:string ] ;
        skos:altLabel [ a xsd:string ] ;
        skos:hiddenLabel [ a xsd:string ] ;
        skos:notation [ a xsd:string ] ;
        skos:note [ a xsd:string ] ;
        skos:changeNote [ a xsd:string ] ;
        skos:definition [ a xsd:string ] ;
        skos:editorialNote [ a xsd:string ] ;
        skos:example [ a xsd:string ] ;
        skos:historyNote [ a xsd:string ] ;
        skos:scopeNote [ a xsd:string ] ;
        skos:semanticRelation [ a skos:Concept ] ;
        skos:broader [ a skos:Concept ] ;
        skos:narrower [ a skos:Concept ] ;
        skos:related [ a skos:Concept ] ;
        skos:broaderTransitive [ a skos:Concept ] ;
        skos:narrowerTransitive [ a skos:Concept ] ;
        skos:mappingRelation [ a skos:Concept ] ;
        skos:broadMatch [ a skos:Concept ] ;
        skos:narrowMatch [ a skos:Concept ] ;
        skos:relatedMatch [ a skos:Concept ] ;
        skos:exactMatch [ a skos:Concept ] ;
        skos:closeMatch [ a skos:Concept ] .
}
WHERE {}