PREFIX def:        <ns/default#>
PREFIX dom:        <ns/domain#>
PREFIX foaf:       <http://xmlns.com/foaf/0.1/>
PREFIX dct:        <http://purl.org/dc/terms/>
PREFIX schema:     <https://schema.org/>
PREFIX dh:         <https://www.w3.org/ns/ldt/document-hierarchy/domain#>
PREFIX sioc:       <http://rdfs.org/sioc/ns#>

CONSTRUCT
{
  ?item a def:Item ;
      sioc:has_container ?this ;
      dh:slug ?id ;
      dct:title ?lastName ;
      foaf:primaryTopic ?employee .
  ?employee foaf:isPrimaryTopicOf ?item ;
      schema:id ?id ;
      schema:givenName ?firstName ;
      schema:familyName ?lastName;
      schema:jobTitle ?title;

      ?titleOfCourtesy

      schema:birthDate ?birthDate;

      ?hireDate

      ?reports

      schema:address [ schema:addressCountry ?country ;
                       schema:addressLocality ?city ;
                       schema:postalCode ?postalCode ;
                       schema:streetAddress ?address ;
                       schema:location [ schema:name ?region ]] ;
      schema:telephone ?homePhone;
      schema:telephone ?extension;
      schema:image ?picture;
      dct:description ?notes.

}
WHERE
{
  BIND (BNODE() AS ?item)

  ?employee <#employeeID> ?id ;
      <#lastName> ?lastName ;
      <#firstName> ?firstName;
      <#title> ?title;
      <#titleOfCourtesy> ?titleOfCourtesy;
      <#birthDate> ?birthDate;
      <#hireDate> ?hireDate;
      <#address> ?address;
      <#city> ?city;
      <#region> ?region;
      <#postalCode> ?postalCode;
      <#country> ?country;
      <#homePhone> ?homephone;
      <#extension> ?extension;
      <#photo> ?picture;
      <#notes> ?notes;
      <#reportsTo> ?reports.

 BIND(uri(concat(str(<employee/>), encode_for_uri(?reports))) AS ?reportsTo)
}
