PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?region
WHERE
  { GRAPH ?doc
      { ?region  a            schema:Place ;
                 schema:name  ?regionDescription
        FILTER NOT EXISTS { ?region schema:containedInPlace [] }
      }
  }
ORDER BY ?regionDescription