PREFIX  schema: <https://schema.org/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  sioc: <http://rdfs.org/sioc/ns#>

SELECT DISTINCT  ?product
WHERE
  { GRAPH ?docGraph
      { ?doc      sioc:has_container  $this ;
                  foaf:primaryTopic   ?product .
        ?product  schema:name         ?productName ;
                  schema:provider     ?supplier ;
                  schema:category     ?category
      }
  }
ORDER BY ?productName