PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  sioc: <http://rdfs.org/sioc/ns#>

SELECT DISTINCT  ?thing
WHERE
  { GRAPH ?childGraph
      {   { ?child  sioc:has_parent  ?this }
        UNION
          { ?child  sioc:has_container  ?this }
        ?child  a                     ?Type ;
            foaf:primaryTopic  ?thing
      }
  }