PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?supplier
WHERE
  { GRAPH ?doc
      { ?supplier  a                schema:Corporation ;
                  schema:legalName  ?companyName
        GRAPH ?productDoc
          { ?product  a                schema:Product ;
                      schema:provider  ?supplier
          }
      }
  }
ORDER BY ?companyName