PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?employee
WHERE
  { GRAPH ?doc
      { ?employee  a                 schema:Person ;
                  schema:familyName  ?lastName
        OPTIONAL
          { ?employee  schema:areaServed  ?territory }
        OPTIONAL
          { ?employee  schema:sponsor  ?reportsToEmployee }
        FILTER NOT EXISTS { GRAPH ?supplierGraph
                              { ?supplier  a               schema:Corporation ;
                                          schema:employee  ?employee
                              }
                          }
      }
  }
ORDER BY ?lastName