PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?category
WHERE
  { GRAPH ?doc
      { ?category  a           schema:ProductGroup ;
                  schema:name  ?categoryName
      }
  }
ORDER BY ?categoryName