PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?territory
WHERE
  { GRAPH ?doc
      { ?territory  schema:name         ?territoryDescription ;
                  schema:containedInPlace  ?region
      }
  }
ORDER BY ?territoryDescription