PREFIX  schema: <https://schema.org/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  sioc: <http://rdfs.org/sioc/ns#>

SELECT DISTINCT  ?customer
WHERE
  { GRAPH ?docGraph
      { ?doc    sioc:has_container  $this ;
                  foaf:primaryTopic   ?customer .
        ?customer  schema:legalName   ?companyName
      }
  }
ORDER BY ?companyName