PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?shipper
WHERE
  { GRAPH ?doc
      { ?shipper  a                 schema:Corporation ;
                  schema:legalName  ?companyName
        GRAPH ?orderDeliveryDoc
          { ?orderDelivery
                      a                schema:ParcelDelivery ;
                      schema:provider  ?shipper
          }
      }
  }
ORDER BY ?companyName