PREFIX  dct:  <http://purl.org/dc/terms/>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT  ?conceptScheme ?doc
WHERE
  { GRAPH ?doc
      { ?conceptScheme
                  a  skos:ConceptScheme
        OPTIONAL
          { ?conceptScheme
                      dct:title  ?title
          }
      }
  }
ORDER BY ?title
