PREFIX  schema: <https://schema.org/>

SELECT DISTINCT  ?product
WHERE
  { GRAPH ?doc
      { ?product  a                schema:Product ;
                  schema:name      ?productName ;
                  schema:provider  ?supplier ;
                  schema:category  ?category
      }
  }
ORDER BY ?productName