PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT  ?concept ?doc
WHERE
  { GRAPH ?doc
      { ?concept
                  a               skos:Collection ;
                  skos:prefLabel  ?prefLabel
      }
  }
ORDER BY ?prefLabel
