PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT  ?collection ?doc
WHERE
  { GRAPH ?doc
      { ?collection
                  a               skos:Collection ;
                  skos:prefLabel  ?prefLabel
        FILTER (langMatches(lang(?prefLabel), "en"))
      }
  }
ORDER BY ?prefLabel
